### ISSUE TITLE
Library missing

### ISSUE THREAD

**Issue by mklissa** [openai/coinrun#20]
Hi there,

I proceed to install the mentionned necessary, but when I try using CoinRun in interactive mode, I get:
```
    from mpi4py import MPI
ImportError: dlopen(/anaconda/envs/coin/lib/python3.6/site-packages/mpi4py/MPI.cpython-36m-darwin.so, 2): Library not loaded: /usr/local/opt/gcc/lib/gcc/7/libgfortran.4.dylib
  Referenced from: /usr/local/opt/mpich/lib/libmpi.12.dylib
  Reason: image not found
```

Thanks

**Comment by christopherhesse** [comment]
Looks like you should uninstall and reinstall mpi, and probably mpi4py as well.  I'm afraid this is not an issue with coinrun.
