### ISSUE TITLE
Easy Way to Control the Procedural Generation

### ISSUE THREAD

**Issue by bhairavmehta95** [openai/coinrun#25]
Is there any easy way to control the parts of the Procedural Generation? I.e force it to generate environments that have (or don't have) certain properties?

**Comment by kcobbe** [comment]
The only way to control the procedural generation right now is to modify the code in coinrun.cpp. If you only want levels with certain properties (e.g. levels that never include moving enemies), you'll have to look there. We currently don't support any interface from Python to C++ for changing the level generation logic, beyond allowing you to specify the set seed, the number of possible levels, and a "high difficulty" flag.
