### ISSUE TITLE
Build on High Sierra

### ISSUE THREAD

**Issue by kvfrans** [openai/coinrun#3]
Hi,

I was trying to build the environment and kept running into this error:
`coinrun.cpp:10:10: fatal error: 'QtCore/QMutexLocker' file not found
#include <QtCore/QMutexLocker>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [.build-release/coinrun.o] Error 1
coinrun: make failed`

The solution ([with help from here](https://github.com/openai/roboschool/issues/110#issuecomment-370108893)) is to 
```
brew install pkg-config
``` 
and then 
```
export PKG_CONFIG_PATH=/usr/local/opt/qt5/lib:/usr/local/opt/qt5/lib/QtWidgets.framework:/usr/local/opt/qt5/lib/pkgconfig
```
Afterwards the environment compiles successfully, on my system at least.

**Comment by christopherhesse** [comment]
The `PKG_CONFIG_PATH` should be set to export `PKG_CONFIG_PATH=/usr/local/opt/qt5/lib/pkgconfig` by default, are those other paths both necessary on your system?

**Comment by christopherhesse** [comment]
@kvfrans ^

**Comment by christopherhesse** [comment]
We added `pkg-config` to the mac dependencies, I'll close this assuming there's nothing else to adjust.
