### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by sanjayyyyyy** [openai/coinrun#32]
I am trying to recreate the performance figure in the paper, How do i get the number of levels solved per time stamp as mentioned in the graph?
Can you please tell me this for both the cases of training and testing, and also how do i get the average rewards per time stamp.?

**Comment by Unimax** [comment]
i am not 100% sure but i think the following is what they did:-

avg reward * 10 = % level solved

avg reward per timestamp = avg reward / avg ep length.

**Comment by kcobbe** [comment]
Unimax is correct that avg reward * 10 = % level solved, since each level of CoinRun has a reward of 10 when successfully completed.
