### ISSUE TITLE
Environment Make Error 1

### ISSUE THREAD

**Issue by Romtein** [openai/coinrun#35]
Hi Team, 
   Am getting this challenge when running the environment any advice?

(base) romtein@romtein-Predator-G3-571:~/coinrun$ python -m coinrun.train_agent --run-id myrun --save-interval 1
Logging to /tmp/openai-2019-05-03-10-51-13-054392
make: Entering directory '/home/romtein/coinrun/coinrun'
gcc -shared -o .build-release/coinrun_cpp.so .build-release/coinrun.o -L/usr/lib64 -lm -lGL -lGLU -lstdc++ `pkg-config --libs Qt5Widgets`
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
Makefile:60: recipe for target '.build-release/coinrun_cpp.so' failed
make: *** [.build-release/coinrun_cpp.so] Error 1
make: Leaving directory '/home/romtein/coinrun/coinrun'
coinrun: make failed

Thank you for your help

**Comment by christopherhesse** [comment]
Looks like you don't have OpenGL installed, could you reinstall the development libraries for opengl?

**Comment by Unimax** [comment]
this helped me with a similar issue: https://stackoverflow.com/questions/33447653/usr-bin-ld-cannot-find-lgl-ubuntu-14-04/33447739

**Comment by christopherhesse** [comment]
So it works now?
