### ISSUE TITLE
How to reset the environment?

### ISSUE THREAD

**Issue by SuiJiGuoChengSuiJiGuo** [openai/coinrun#37]
Hi Team,
I am trying to read the code of this project, but when I read the ppo2.py, I have a little doubt about class Runner. I can't distinguish when will environments reset in the function run(). And if one of the environments in parallel will done, what about others will be? 
thanks

**Comment by christopherhesse** [comment]
In the `VecEnv` interface, each instance of the environment resets itself on done, so there should be no need for `Runner` to call `venv.reset()`
