### ISSUE TITLE
Not working on Windows 10

### ISSUE THREAD

**Issue by MarcoMeter** [openai/coinrun#38]
Hello everybody,

running `python -m coinrun.interactive` on Windows outputs this error:

```
'QT_SELECT' is not recognized as an internal or external command,
operable program or batch file.
coinrun: make failed
```

This is how I installed Qt:

1. Download qt-opensource-windows-x86-5.13.1
https://www.qt.io/offline-installers

2. Install Qt

![Qt](https://user-images.githubusercontent.com/6996955/65487227-bab6f280-dea6-11e9-991c-538ec023c2e9.png)

3. Restart

Also, I installed GnuWin32 using the complete package setup
http://gnuwin32.sourceforge.net/packages/make.htm

Did anybody got CoinRun working on Windows yet?

**Comment by MarcoMeter** [comment]
I also tried running the os command without "QT_SELECT=5" and that raised this issue:

```
process_begin: CreateProcess(NULL, uname -s, ...) failed.
make: Entering directory `D:/Pleines/Repositories/coinrun/coinrun'
o .generated/coinrun.moc coinrun.cpp
process_begin: CreateProcess(NULL, o .generated/coinrun.moc coinrun.cpp, ...) failed.
make (e=2): The system cannot find the file specified.
make: [.generated/coinrun.moc] Error 2 (ignored)
gcc -std=c++11 -Wall -Wno-unused-variable -Wno-unused-function -Wno-deprecated-register -fPIC -g -O3 -march=native ` --cflags Qt5Widgets` -c coinrun.cpp  -o.build-release/coinrun.o -MMD -MF .build-release/coinrun.o.dep
gcc: error: `: No such file or directory
gcc: error: Qt5Widgets`: No such file or directory
gcc: error: unrecognized command line option '--cflags'
make: *** [.build-release/coinrun.o] Error 1
make: Leaving directory `D:/Pleines/Repositories/coinrun/coinrun'
coinrun: make failed
```

**Comment by ghost** [comment]
I also tried to run it on Windows 10. But after several tries including different versions and environment settings, I guess qt5 on windows can't support to run this project... Waiting for an official reply...

**Comment by christopherhesse** [comment]
I'm afraid windows isn't a supported platform for this release, please try out https://github.com/openai/procgen which does support windows.
