### ISSUE TITLE
Pypi, version and qt

### ISSUE THREAD

**Issue by TimZaman** [openai/coinrun#8]
Hello, Nice project!

Not an issue, but you should

1. Add a package version in the package; e.g. so you can do `coinrun.__version__`.
2. Upload to pypi to make sure you claim the package name.

Why did this depend on Qt? For such a simple game you could have gone for something more lightweight and with a better licence no?

From the readme saying "Status: archive", it almost seems like this project was DOA and dropped on Github? What's the story?

**Comment by christopherhesse** [comment]
Like most of our code releases for papers, we do not currently have plans to make this a pypi package, though thank you for the suggestion!  The status is also the same as our other releases of code associated with papers.

**Comment by TimZaman** [comment]
Do you accept contributions? I can help upload it.

**Comment by sjtuytc** [comment]
> Do you accept contributions? I can help upload it.

Can you tell me how to use this repo without qt5 installed? Or can you share your repo?
